export default [
  {
    name: "Default",
    value: {
      song:"https://donkey-spaces.ams3.cdn.digitaloceanspaces.com/assets/travel-clip/travel.mp3",
      colorText:"white",
      mixBlendColor:"black",
      backgroundColor:"#101010",
      title1: "TRAVEL",
      subtitle1:"WITH FRIENDS",
      title2:"COLLECT",
      subtitle2:"MOMENTS",
      text3:"DISCOVER NEW PLACES",
      text4:["TRAVEL","IS","LIFE"],
      title5a:"ADVENTURE",
      title5b:"AWAITS",
      text6:["LIVE","EVERY","MOMENT"],
      text7:"ROAD TRIPS",
      text8:"TAKE PICTURES",
      img1:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/boots.gif?raw=true",
      img2_7:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/girl-car.gif?raw=true",
      img3:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/clothes.gif?raw=true",
      img4_33:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/girl-map.jpeg?raw=true",
      img5:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/girl-road.jpeg?raw=true",
      img6_34:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/girl-camera.gif?raw=true",
      img8_11:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/woman-mountain.png?raw=true",
      img9:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/woman-caravan.gif?raw=true",
      img10_36:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/travel-with-friends.gif?raw=true",
      img12:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/ballons.gif?raw=true",
      img13:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/friends-road.png?raw=true",
      img14:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/inside-caravan.png?raw=true",
      img15:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/woman-and-man.jpeg?raw=true",
      img30:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/caravan-dog.png?raw=true",
      img16:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/map.gif?raw=true",
      img17:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/woman-snow.jpeg?raw=true",
      img37:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/mountain-breath.jpeg?raw=true",
      img18_35:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/woman-road.gif?raw=true",
      img19_28:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/photo.jpeg?raw=true",
      img20:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/woman-caravan.gif?raw=true",
      img21_22:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/girl-with-map-car.gif?raw=true",
      img23:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/friends-nature.png?raw=true",
      img24:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/girl-flowers.png?raw=true",
      img25:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/girl-guitar.png?raw=true",
      img26:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/fire.png?raw=true",
      img27:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/caravan-friends.jpeg?raw=true",
      img29:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/caravan-road.png?raw=true",
      img31:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/road-trip.jpeg?raw=true",
      img32:"https://github.com/donkeyclip/travel-clip/blob/main/demo/assets/friends.jpeg?raw=true"
    },
  }
];
