export default {
    song: {
      label: "Song",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/travel.mp3",
    },
    colorText: {
      label: "Text Color",
      type: "color",
      optional: true,
      default: "white",
    },
    mixBlendColor: {
      label: "Mix Blend Color",
      type: "color",
      optional: true,
      default: "black",
    },
    backgroundColor: {
      label: "Background Color",
      type: "color",
      optional: true,
      default: "#101010",
    },
    title1a: {
      label: "1st Title Part A",
      type: "string",
      optional: true,
      default: "TRAVEL",
    },
    title1b: {
      label: "1st Title Part B",
      type: "string",
      optional: true,
      default: "WITH FRIENDS",
    },
    title2a: {
      label: "2nd Title Part A",
      type: "string",
      optional: true,
      default: "COLLECT",
    },
    title2b: {
      label: "2nd Title Part B",
      type: "string",
      optional: true,
      default: "MOMENTS",
    },
    title3: {
      label: "3rd Title",
      type: "string",
      optional: true,
      default: "DISCOVER NEW PLACES",
    },
    title4: {
      label: "4th Title",
      type: "array",
      optional: true,
      default: ["TRAVEL","IS","LIFE"],
      items: "string",
    },
    title5a: {
      label: "5th Title Part A",
      type: "string",
      optional: true,
      default: "ADVENTURE",
    },
    title5b: {
      label: "5th Title Part B",
      type: "string",
      optional: true,
      default: "AWAITS",
    },
    title6: {
      label: "6th Title",
      type: "array",
      optional: true,
      default: ["LIVE","EVERY","MOMENT"],
      items: "string",
    },
    title7: {
      label: "7th Title",
      type: "string",
      optional: true,
      default: "ROAD TRIPS",
    },
    title8: {
      label: "8th Title",
      type: "string",
      optional: true,
      default: "TAKE PICTURES",
    },
    img1: {
      label: "Image 1",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/boots.gif",
    },
    img2_7: {
      label: "Image 2",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/girl-car.gif",
    },
    img3: {
      label: "Image 3",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/clothes.gif",
    },
    img4_33: {
      label: "Image 4",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/girl-map.jpeg",
    },
    img5: {
      label: "Image 5",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/girl-road.jpeg",
    },
    img6_34: {
      label: "Image 6",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/girl-camera.gif",
    },
    img8_11: {
      label: "Image 7",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/woman-mountain.png",
    },
    img9: {
      label: "Image 8",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/woman-caravan.gif",
    },
    img10_36: {
      label: "Image 9",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/travel-with-friends.gif",
    },
    img12: {
      label: "Image 10",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/ballons.gif",
    },
    img13: {
      label: "Image 11",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/friends-road.png",
    },
    img14: {
      label: "Image 12",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/inside-caravan.png",
    },
    img15: {
      label: "Image 13",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/woman-and-man.jpeg",
    },
    img16: {
      label: "Image 14",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/map.gif",
    },
    img17: {
      label: "Image 15",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/woman-snow.jpeg",
    },
    img18_35: {
      label: "Image 16",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/woman-road.gif",
    },
    img19_28: {
      label: "Image 17",
      type: "string",
      optional: true,
      default:"https://donkeyclip.github.io/travel-clip/demo/assets/photo.jpeg",
    },
    img20: {
      label: "Image 18",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/woman-caravan.gif",
    },
    img21_22: {
      label: "Image 19",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/girl-with-map-car.gif",
    },
    img23: {
      label: "Image 20",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/friends-nature.png",
    },
    img24: {
      label: "Image 21",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/girl-flowers.png",
    },
    img25: {
      label: "Image 22",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/girl-guitar.png",
    },
    img26: {
      label: "Image 23",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/fire.png",
    },
    img27: {
      label: "Image 24",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/caravan-friends.jpeg",
    },
    img29: {
      label: "Image 25",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/caravan-road.png",
    },
    img30: {
      label: "Image 26",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/caravan-dog.png",
    },
    img31: {
      label: "Image 27",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/road-trip.jpeg",
    },
    img32: {
      label: "Image 28",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/friends.jpeg",
    },
    img37: {
      label: "Image 29",
      type: "string",
      optional: true,
      default: "https://donkeyclip.github.io/travel-clip/demo/assets/mountain-breath.jpeg",
    },
  }; 