export default [
  {
    name: "Default",
    value: {
      song:"https://donkeyclip.github.io/travel-clip/demo/assets/travel.mp3",
      colorText:"white",
      mixBlendColor:"black",
      backgroundColor:"#101010",
      title1: "TRAVEL",
      subtitle1:"WITH FRIENDS",
      title2:"COLLECT",
      subtitle2:"MOMENTS",
      text3:"DISCOVER NEW PLACES",
      text4:["TRAVEL","IS","LIFE"],
      title5a:"ADVENTURE",
      title5b:"AWAITS",
      text6:["LIVE","EVERY","MOMENT"],
      text7:"ROAD TRIPS",
      text8:"TAKE PICTURES",
      img1:"https://donkeyclip.github.io/travel-clip/demo/assets/boots.gif",
      img2_7:"https://donkeyclip.github.io/travel-clip/demo/assets/girl-car.gif",
      img3:"https://donkeyclip.github.io/travel-clip/demo/assets/clothes.gif",
      img4_33:"https://donkeyclip.github.io/travel-clip/demo/assets/girl-map.jpeg",
      img5:"https://donkeyclip.github.io/travel-clip/demo/assets/girl-road.jpeg",
      img6_34:"https://donkeyclip.github.io/travel-clip/demo/assets/girl-camera.gif",
      img8_11:"https://donkeyclip.github.io/travel-clip/demo/assets/woman-mountain.png",
      img9:"https://donkeyclip.github.io/travel-clip/demo/assets/woman-caravan.gif",
      img10_36:"https://donkeyclip.github.io/travel-clip/demo/assets/travel-with-friends.gif",
      img12:"https://donkeyclip.github.io/travel-clip/demo/assets/ballons.gif",
      img13:"https://donkeyclip.github.io/travel-clip/demo/assets/friends-road.png",
      img14:"https://donkeyclip.github.io/travel-clip/demo/assets/inside-caravan.png",
      img15:"https://donkeyclip.github.io/travel-clip/demo/assets/woman-and-man.jpeg",
      img30:"https://donkeyclip.github.io/travel-clip/demo/assets/caravan-dog.png",
      img16:"https://donkeyclip.github.io/travel-clip/demo/assets/map.gif",
      img17:"https://donkeyclip.github.io/travel-clip/demo/assets/woman-snow.jpeg",
      img37:"https://donkeyclip.github.io/travel-clip/demo/assets/mountain-breath.jpeg",
      img18_35:"https://donkeyclip.github.io/travel-clip/demo/assets/woman-road.gif",
      img19_28:"https://donkeyclip.github.io/travel-clip/demo/assets/photo.jpeg",
      img20:"https://donkeyclip.github.io/travel-clip/demo/assets/woman-caravan.gif",
      img21_22:"https://donkeyclip.github.io/travel-clip/demo/assets/girl-with-map-car.gif",
      img23:"https://donkeyclip.github.io/travel-clip/demo/assets/friends-nature.png",
      img24:"https://donkeyclip.github.io/travel-clip/demo/assets/girl-flowers.png",
      img25:"https://donkeyclip.github.io/travel-clip/demo/assets/girl-guitar.png",
      img26:"https://donkeyclip.github.io/travel-clip/demo/assets/fire.png",
      img27:"https://donkeyclip.github.io/travel-clip/demo/assets/caravan-friends.jpeg",
      img29:"https://donkeyclip.github.io/travel-clip/demo/assets/caravan-road.png",
      img31:"https://donkeyclip.github.io/travel-clip/demo/assets/road-trip.jpeg",
      img32:"https://donkeyclip.github.io/travel-clip/demo/assets/friends.jpeg"
    },
  }
];
